// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCarJWV0pAlAIdFltDRALGDD-QmKmA4H3M',
    appId: '1:976838111237:web:c56860ade9309981a72c6c',
    messagingSenderId: '976838111237',
    projectId: 'blended-learning-app-15f2c',
    authDomain: 'blended-learning-app-15f2c.firebaseapp.com',
    storageBucket: 'blended-learning-app-15f2c.appspot.com',
    measurementId: 'G-EV5BBEQGQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Gyse8Scxf9ZX7bBY0TByzk5CdOLJmUA',
    appId: '1:976838111237:android:787a00b53e637b74a72c6c',
    messagingSenderId: '976838111237',
    projectId: 'blended-learning-app-15f2c',
    storageBucket: 'blended-learning-app-15f2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANyHPG28ODNBM1WPuvyUSKH11bWxm_Sco',
    appId: '1:976838111237:ios:03b413f755572a4ba72c6c',
    messagingSenderId: '976838111237',
    projectId: 'blended-learning-app-15f2c',
    storageBucket: 'blended-learning-app-15f2c.appspot.com',
    iosBundleId: 'com.example.blendedLearningAppmb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANyHPG28ODNBM1WPuvyUSKH11bWxm_Sco',
    appId: '1:976838111237:ios:03b413f755572a4ba72c6c',
    messagingSenderId: '976838111237',
    projectId: 'blended-learning-app-15f2c',
    storageBucket: 'blended-learning-app-15f2c.appspot.com',
    iosBundleId: 'com.example.blendedLearningAppmb',
  );

  /*
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCarJWV0pAlAIdFltDRALGDD-QmKmA4H3M',
    appId: '1:976838111237:web:05002a1205951ddda72c6c',
    messagingSenderId: '976838111237',
    projectId: 'blended-learning-app-15f2c',
    authDomain: 'blended-learning-app-15f2c.firebaseapp.com',
    storageBucket: 'blended-learning-app-15f2c.appspot.com',
    measurementId: 'G-QDDH0SZD3F',
  );*/

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyCarJWV0pAlAIdFltDRALGDD-QmKmA4H3M",
      authDomain: "blended-learning-app-15f2c.firebaseapp.com",
      projectId: "blended-learning-app-15f2c",
      storageBucket: "blended-learning-app-15f2c.appspot.com",
      messagingSenderId: "976838111237",
      appId: "1:976838111237:web:05002a1205951ddda72c6c",
      measurementId: "G-QDDH0SZD3F"
  );
}
